jobs:
  deployAarsToNexus:
    needs: generateReadme
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
    - continue-on-error: true
      env:
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        OSSR_PASSWORD: ${{ secrets.OSSR_PASSWORD }}
        OSSR_USERNAME: ${{ secrets.OSSR_USERNAME }}
        SONATYPE_STATING_PROFILE_ID: ${{ secrets.SONATYPE_STATING_PROFILE_ID }}
      run: 'echo "${{ secrets.GPG_FILE }}" > sec.gpg.asc

        gpg -d --passphrase "${{ secrets.GPG_FILE_PSWD }}" --batch sec.gpg.asc > sec.gpg

        fastlane deployNexus

        '
      shell: bash
  generateReadme:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
    - continue-on-error: true
      run: 'git config user.email mag@nordicsemi.no

        git config user.name "Github Action"

        VERSION=`git describe --tags --abbrev=0`

        VERSION=`./moustache/split.sh $VERSION`

        rm -f ./README.md

        VERSION=$VERSION ./moustache/mo ./moustache/README.mo > ./README.md

        git add .

        git diff-index --quiet HEAD || git commit -m "Update readme to version=$VERSION"
        && git push

        '
      shell: bash
name: Deploy to Nexus
on:
  repository_dispatch:
    types: trigger-ga___deploy-all.yml
